### ISSUE TITLE
Breaking change for Linux with introduction of the wres package

### ISSUE THREAD

**Issue by martinbrose** [tevslin/cloudflarepycli#1]
Thanks for writing this little helper class for the cloudflare speedtest.

I received the following error when I tried to use it on a Mac:
```
Traceback (most recent call last):
  File "/Users/martinbrose/opt/anaconda3/envs/speedtest/bin/cfspeedtest", line 8, in <module>
    sys.exit(main())
  File "/Users/martinbrose/opt/anaconda3/envs/speedtest/lib/python3.9/site-packages/cloudflarepycli/__main__.py", line 35, in main
    thedict=thetester.runalltests()
  File "/Users/martinbrose/opt/anaconda3/envs/speedtest/lib/python3.9/site-packages/cloudflarepycli/cloudflareclass.py", line 154, in runalltests
    fulltimes,servertimes,requesttimes=self.download(1,self.latencyreps) #measure latency and jitter
  File "/Users/martinbrose/opt/anaconda3/envs/speedtest/lib/python3.9/site-packages/cloudflarepycli/cloudflareclass.py", line 101, in download
    import wres  
  File "/Users/martinbrose/opt/anaconda3/envs/speedtest/lib/python3.9/site-packages/wres/__init__.py", line 16, in <module>
    ntdll = ctypes.WinDLL('NTDLL.DLL')
AttributeError: module 'ctypes' has no attribute 'WinDLL'
```
I think you introduced a Windows DLL dependency in commit 841f4525cbcf522a0290cb823d3312bdacf9b5c6 when you added `import wres`. Was this intentional?

Your PyPI version 1.0.3 works fine, but version 1.6.0 won't run on Linux machines.

**Comment by tevslin** [comment]
> Thanks for writing this little helper class for the cloudflare speedtest.
> 
> I received the following error when I tried to use it on a Mac / Linux machine:
> 
> ```
> Traceback (most recent call last):
>   File "/home/vagrant/anaconda3/envs/speedtest/bin/cfspeedtest", line 8, in <module>
>     sys.exit(main())
>   File "/home/vagrant/anaconda3/envs/speedtest/lib/python3.8/site-packages/cloudflarepycli/__main__.py", line 35, in main
>     thedict=thetester.runalltests()
>   File "/home/vagrant/anaconda3/envs/speedtest/lib/python3.8/site-packages/cloudflarepycli/cloudflareclass.py", line 154, in runalltests
>     fulltimes,servertimes,requesttimes=self.download(1,self.latencyreps) #measure latency and jitter
>   File "/home/vagrant/anaconda3/envs/speedtest/lib/python3.8/site-packages/cloudflarepycli/cloudflareclass.py", line 101, in download
>     import wres  
>   File "/home/vagrant/anaconda3/envs/speedtest/lib/python3.8/site-packages/wres/__init__.py", line 16, in <module>
>     ntdll = ctypes.WinDLL('NTDLL.DLL')
> AttributeError: module 'ctypes' has no attribute 'WinDLL'
> ```
> 
> I think you introduced a Windows DLL dependency in commit [841f452](https://github.com/tevslin/cloudflarepycli/commit/841f4525cbcf522a0290cb823d3312bdacf9b5c6) when you added `import wres`. Was this intentional?
> 
> Your PyPI version 1.0.3 works fine, but version 1.6.0 won't run on Linux machines.

Hi Martin.

Thanks for the note, Although it's on my todo list, I don't have a date yet for Mac and Linux compatible versions of anything I've got on github. I added wres because, without it, I wasn't getting good enough time resolution without it; but you are absolutely correct that it is Windows dependent,

**Comment by martinbrose** [comment]
Ok, if you want to keep Linux / Mac user, then please consider my pull request.

**Comment by sinnx3** [comment]
Any update on this issue @tevslin? As of this writing this issue also breaks WSL 1.0/2.0 usability. 

Using @martinbrose  #3 PR works fixing the above issue(s).

Also, I'd like to add that there is a sporadic error with using the above pr that I haven't seen with main branch and that is:

`/home/sinnx3/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/sinnx3/.local/lib/python3.8/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)`
